version: '3.4'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
        environment:
            - NGINXUSER=svd
            - NGINXGROUP=svd
        depends_on:
            - mysql
            - php
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        build:
            context: .
            dockerfile: php.Dockerfile
        environment:
            - PHPUSER=svd
            - PHPGROUP=svd
        volumes:
            - ./src:/var/www/html
    composer:
        build:
            context: .
            dockerfile: composer.Dockerfile
        environment:
            - COMPOSERUSER=svd
            - COMPOSERGROUP=svd
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
    npm:
        image: node:current-alpine
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ["npm"]
    artisan:
        build:
            context: .
            dockerfile: php.Dockerfile
        environment:
            - PHPUSER=svd
            - PHPGROUP=svd
        volumes:
            - ./src:/var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]

